### PR TITLE
Lazy static completions

### PR DESCRIPTION
**Pull request by lavafroth**
### Changes
- Replace `HX_TAGS`, `HX_ATTRIBUTE_VALUES` and `TEXT_STORE` from being `OnceLock`s to being lazy statics
- `init_text_store` and `init_hx_tags` are now implicit
- Lazy statics no longer require `.get()` for accessing attributes

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
could we break these up into 2 prs?

please do the lazy statics.  i like that change a lot :)

then we can avoid the clones

**Comment by lavafroth** [comment]
The point about lesser clones is a by-product of using lazy statics. The lazy static forces the use of static string slices in the cases I mentioned unless one goes out of their way to clone things. 😅

**Comment by lavafroth** [comment]
Also, it would be better in the long run to have the binary representation of the completion structs embedded in the final executable during comptime so we don't have to call '.leak()' on the completions vector. We could use the [`include!`](https://doc.rust-lang.org/std/macro.include.html) macro to do something like that.

**Comment by ThePrimeagen** [comment]
ok, very interesting.  i am going to try to review this once more and make sure i get what is going on.  :)

i may just need to download it and look at it in my editor

**Comment by ThePrimeagen** [comment]
i am also going to get #22  merged in first.  

may cause conflict, sorry

**Comment by lavafroth** [comment]
Sure thing! I've synced this branch with upstream.

**Comment by ThePrimeagen** [comment]
psst, sorry about not merging this

if you remove the conflicts, i can help get this in

**Comment by lavafroth** [comment]
Sure, I'll resolve the conflicts by tomorrow.

**Comment by lavafroth** [comment]
I'm only considering the inclusion of lazy static for now, if I try to add more changes this PR becomes really massive.

**Comment by lavafroth** [comment]
Hey just a heads up, it looks like OnceCell / OnceLock are actually more mature for our use case. There's also [talk about deprecating lazy_static](https://github.com/rust-lang-nursery/lazy-static.rs/issues/214). Sorry for troubling you, I'm closing this.

**Pull request closed without merging**
